name: 'update-container-versions-binoc'

on:
  schedule:
    # Delayed Binoc execution time to mid day just in case we need to step in.
    - cron: '0 20 * * *'
  push:
    branches: main


jobs:
  auto-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Run Binoc Scan
        uses: autamus/binoc@v0.2.0
        with:
          git_token: ${{ secrets.BINOC_GIT_TOKEN }}
          git_username: ${{ secrets.BINOC_GIT_USERNAME }}
          git_email: ${{ secrets.BINOC_GIT_EMAIL }}
          git_name: ${{ secrets.BINOC_GIT_NAME }}
          general_action: 'true'
          parsers_loaded: 'shpc'
